context.objects = [
    {
        factory = adapter
        args = {
            factory.name    = support.null-audio-sink
            node.name       = "toTRX"
            object.linger   = true
            node.description = "To Radio"
            audio.rate      = 48000
            audio.format    = S16LE
            audio.channels  = 2
            latency.internal = 128
            latency.min     = 128
            latency.max     = 512
        }
    },
    {
        factory = adapter
        args = {
            factory.name    = support.null-audio-sink
            node.name       = "fromTRX"
            object.linger   = true
            node.description = "From Radio"
            audio.rate      = 48000
            audio.format    = S16LE
            audio.channels  = 2
            latency.internal = 128
            latency.min     = 128
            latency.max     = 512
        }
    }
]
